# Generated by Django 2.1.2 on 2020-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_meal_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
