# Generated by Django 2.1.2 on 2020-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20200314_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='shop',
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='shop',
            field=models.TextField(default='', max_length=50),
        ),
    ]
