# Generated by Django 2.1.2 on 2020-03-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20200314_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Shop'),
        ),
    ]
