# Generated by Django 2.1.2 on 2020-03-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_auto_20200314_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealingredient',
            name='shop',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meals.Shop'),
        ),
    ]
