# Generated by Django 2.1.2 on 2020-02-20 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('make', models.TextField(blank=True, max_length=100, null=True)),
                ('model', models.TextField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('engine', models.TextField(blank=True, max_length=100, null=True)),
                ('power', models.FloatField(blank=True, default=None, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('sold', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liters', models.FloatField()),
                ('kilometers', models.FloatField()),
                ('fuel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=160)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('labour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=160)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Service')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Service'),
        ),
    ]
