# Generated by Django 2.1.2 on 2020-02-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200220_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=160)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('labour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=160)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Service')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Service'),
        ),
    ]
