# Generated by Django 2.1.2 on 2020-02-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200220_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='service_id',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SparePart',
        ),
    ]
